package org.hemit.domain.model.exceptions

class ParticipantAlreadyExistsForTournamentError : Exception()
